FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10 \
    libc6

COPY cmake/x86_64-unknown-linux-gnu.cmake /toolchains
COPY cmake/x86_64-unknown-linux-gnu.cmake /toolchains/x86_64.cmake
COPY env/x86_64-unknown-linux-gnu /toolchains/env
