FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/i386-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=i386-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Add symlinks and toolchains
