FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/avr.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=avr /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng

# Add toolchains
COPY cmake/avr.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains
COPY cmake/static.cmake /toolchains
COPY env/avr /env/toolchain
COPY env/alias /env
COPY env/shared /env
COPY env/static /env
