FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/sparc64-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=sparc64-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/sparc64-unknown.cmake /toolchains
#COPY cmake/sparc64-unknown.cmake /toolchains/sparc64.cmake
#COPY env/sparc64-unknown /toolchains/env
