FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mipsisa32r6-linux-gnu \
    libc6-mipsr6-cross

# Add symlinks
COPY symlink/exec.sh /
COPY symlink/mipsr6-unknown-linux-gnu.sh /
RUN /mipsr6-unknown-linux-gnu.sh
RUN rm /exec.sh /mipsr6-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/mipsr6-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
