FROM ahuszagh/cross:base

# Build GCC
COPY android.sh /
RUN /android.sh
RUN rm /android.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/x86_64-unknown-linux-android.sh /
RUN /x86_64-unknown-linux-android.sh
RUN rm /shortcut.sh /x86_64-unknown-linux-android.sh

# Add toolchains
COPY cmake/x86_64-unknown-linux-android.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
