FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/shbe-unknown-elf.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=shbe-unknown-elf /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
#COPY cmake/sh-unknown-elf.cmake /toolchains
#COPY env/sh-unknown-elf /toolchains/env
#COPY cmake/sh-unknown-elf.cmake /toolchains/sh.cmake
