FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/sh3eb-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=sh3eb-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/sh3eb-unknown.cmake /toolchains
#COPY cmake/sh3eb-unknown.cmake /toolchains/sh3eb.cmake
#COPY env/sh3eb-unknown /toolchains/env
