FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mips-linux-gnu \
    libc6-mips-cross

# Add symlinks
COPY symlink/exec.sh /
COPY symlink/mips-unknown-linux-gnu.sh /
RUN /mips-unknown-linux-gnu.sh
RUN rm /exec.sh /mips-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/mips-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
