FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-alpha-linux-gnu \
    libc6.1-alpha-cross

COPY cmake/alpha-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains
COPY cmake/static.cmake /toolchains
COPY env/alpha-unknown-linux-gnu /env/toolchain
COPY env/alias /env
COPY env/shared /env
COPY env/static /env

