FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/nios2-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=nios2-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/nios2-unknown.cmake /toolchains
#COPY cmake/nios2-unknown.cmake /toolchains/nios2.cmake
#COPY env/nios2-unknown /toolchains/env
