FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/ppc-unknown-elf.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=ppc-unknown-elf /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/ppc-unknown-elf.cmake /toolchains
#COPY cmake/ppc-unknown-elf.cmake /toolchains/ppc.cmake
#COPY env/ppc-unknown-elf /toolchains/env
