FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-m68k-linux-gnu \
    libc6-m68k-cross

COPY cmake/m68k-unknown-linux-gnu.cmake /toolchains
COPY cmake/m68k-unknown-linux-gnu.cmake /toolchains/m68k.cmake
COPY env/m68k-unknown-linux-gnu /toolchains/env
