FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-sparc64-linux-gnu \
    libc6-sparc64-cross

COPY cmake/sparc64.cmake /toolchains
