FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-powerpc64-linux-gnu \
    libc6-ppc64-cross

COPY cmake/ppc64.cmake /toolchains
