FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/sh2-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=sh2-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/sh2-unknown.cmake /toolchains
#COPY cmake/sh2-unknown.cmake /toolchains/sh2.cmake
#COPY env/sh2-unknown /toolchains/env
