FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/sh-unknown-elf.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=sh-unknown-elf /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
COPY cmake/sh4-200-unknown-elf.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains
COPY cmake/static.cmake /toolchains
COPY env/sh-unknown-elf /env/sh
COPY env/sh4-200-unknown-elf /env/toolchain
COPY env/alias /env
COPY env/shared /env
COPY env/static /env

