FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mipsel-linux-gnu \
    libc6-mipsel-cross

COPY cmake/mipsel-unknown-linux-gnu.cmake /toolchains
COPY cmake/mipsel-unknown-linux-gnu.cmake /toolchains/mipsel.cmake
COPY env/mipsel-unknown-linux-gnu /toolchains/env
