FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/mips64-unknown-n32.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=mips64-unknown-n32 /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/mips64-unknown-n32.cmake /toolchains
#COPY cmake/mips64-unknown-n32.cmake /toolchains/mips64.cmake
#COPY env/mips64-unknown-n32 /toolchains/env
