FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/arc-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=arc-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/arc-unknown.cmake /toolchains
#COPY cmake/arc-unknown.cmake /toolchains/arc.cmake
#COPY env/arc-unknown /toolchains/env
