FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-hppa-linux-gnu \
    libc6-hppa-cross

COPY cmake/hppa-unknown-linux-gnu.cmake /toolchains
COPY cmake/hppa-unknown-linux-gnu.cmake /toolchains/hppa.cmake
COPY env/hppa-unknown-linux-gnu /toolchains/env
