FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mipsisa32r6el-linux-gnu \
    libc6-mipsr6el-cross

COPY cmake/mipsr6el-unknown-linux-gnu.cmake /toolchains
COPY cmake/mipsr6el-unknown-linux-gnu.cmake /toolchains/mipsr6el.cmake
COPY env/mipsr6el-unknown-linux-gnu /toolchains/env
