FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/mips64el-unknown-n32.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=mips64el-unknown-n32 /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Add symlinks and toolchains
