FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/mips-unknown-o32.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=mips-unknown-o32 /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/mips-unknown-o32.cmake /toolchains
#COPY cmake/mips-unknown-o32.cmake /toolchains/mips.cmake
#COPY env/mips-unknown-o32 /toolchains/env
