FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-powerpc-linux-gnu \
    libc6-powerpc-cross

COPY cmake/ppc.cmake /toolchains
