FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mipsisa32r6-linux-gnu \
    libc6-mipsr6-cross

COPY cmake/mipsr6.cmake /toolchains
