FROM ahuszagh/cross:qemu

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-powerpc64-linux-gnu \
    libc6-ppc64-cross

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/ppc64-unknown-linux-gnu.sh /
RUN /ppc64-unknown-linux-gnu.sh
RUN rm /shortcut.sh /ppc64-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/ppc64-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
