FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-sh4-linux-gnu \
    libc6-sh4-cross

# Add toolchains
COPY cmake/sh4-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains
COPY cmake/static.cmake /toolchains
COPY env/sh4-unknown-linux-gnu /env/toolchain
COPY env/alias /env
COPY env/shared /env
COPY env/static /env
