FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-powerpc64le-linux-gnu \
    libc6-ppc64el-cross

# Add toolchains
COPY cmake/ppc64le-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains
COPY cmake/static.cmake /toolchains
COPY env/ppc64le-unknown-linux-gnu /env/toolchain
COPY env/alias /env
COPY env/shared /env
COPY env/static /env
