FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/m68k-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=m68k-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/m68k-unknown.cmake /toolchains
#COPY cmake/m68k-unknown.cmake /toolchains/m68k.cmake
#COPY env/m68k-unknown /toolchains/env
