FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/xtensabe-unknown-linux-uclibc.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=xtensabe-unknown-linux-uclibc /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore...
#COPY cmake/xtensabe-unknown-linux-uclibc.cmake /toolchains/toolchain.cmake
#COPY cmake/shared.cmake /toolchains
#COPY cmake/static.cmake /toolchains
#COPY env/xtensabe-unknown-linux-uclibc /env/toolchain
#COPY env/alias /env
#COPY env/shared /env
#COPY env/static /env
