FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/powerpcle-unknown-eabi.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=powerpcle-unknown-eabi /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
COPY cmake/ppcle-unknown-eabi.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains
COPY cmake/static.cmake /toolchains
COPY env/ppcle-unknown-eabi /env/toolchain
COPY env/alias /env
COPY env/shared /env
COPY env/static /env
