FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/m68k-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=m68k-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/m68k-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
#COPY cmake/shared.cmake /toolchains
#COPY cmake/static.cmake /toolchains
#COPY env/m68k-unknown-linux-gnu /env/toolchain
#COPY env/alias /env
#COPY env/shared /env
#COPY env/static /env
