FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/i586-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=i586-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/i586-unknown.cmake /toolchains
#COPY cmake/i586-unknown.cmake /toolchains/i586.cmake
#COPY env/i586-unknown /toolchains/env
