FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/ppc-unknown-eabi.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=ppc-unknown-eabi /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/ppc-unknown-eabi.cmake /toolchains
#COPY cmake/ppc-unknown-eabi.cmake /toolchains/x86_64.cmake
#COPY env/ppc-unknown-eabi /toolchains/env
