FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/s390x-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=s390x-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/s390x-unknown.cmake /toolchains
#COPY cmake/s390x-unknown.cmake /toolchains/s390x.cmake
#COPY env/s390x-unknown /toolchains/env
