FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-riscv64-linux-gnu \
    libc6-riscv64-cross

COPY cmake/riscv64-unknown-linux-gnu.cmake /toolchains
COPY cmake/riscv64-unknown-linux-gnu.cmake /toolchains/riscv64.cmake
COPY env/riscv64-unknown-linux-gnu /toolchains/env
