FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-riscv64-linux-gnu \
    libc6-riscv64-cross

COPY cmake/riscv64.cmake /toolchains
