FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/i486-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=i486-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/i486-unknown.cmake /toolchains
#COPY cmake/i486-unknown.cmake /toolchains/i486.cmake
#COPY env/i486-unknown /toolchains/env
