FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/i686-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=i686-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/i686-unknown.cmake /toolchains
#COPY cmake/i686-unknown.cmake /toolchains/i686.cmake
#COPY env/i686-unknown /toolchains/env
