FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/s390-unknown-linux-gnu.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=s390-unknown-linux-gnu /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
COPY cmake/s390-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains
COPY cmake/static.cmake /toolchains
COPY env/s390-unknown-linux-gnu /env/toolchain
COPY env/alias /env
COPY env/shared /env
COPY env/static /env
