FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/ppc64le-unknown-elf.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=ppc64le-unknown-elf /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/ppc64le-unknown-elf.cmake /toolchains
#COPY cmake/ppc64le-unknown-elf.cmake /toolchains/x86_64.cmake
#COPY env/ppc64le-unknown-elf /toolchains/env
