FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/alphaev5-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=alphaev5-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/alphaev5-unknown.cmake /toolchains
#COPY cmake/alphaev5-unknown.cmake /toolchains/alphaev5.cmake
#COPY env/alphaev5-unknown /toolchains/env
