FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/xtensale-unknown-linux-uclibc.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=xtensale-unknown-linux-uclibc /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Restore...
## Add toolchains
#COPY cmake/xtensale-unknown-linux-uclibc.cmake /toolchains
#COPY cmake/xtensale-unknown-linux-uclibc.cmake /toolchains/xtensale.cmake
#COPY env/xtensale-unknown-linux-uclibc /toolchains/env
