FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mips-linux-gnu \
    libc6-mips-cross

COPY cmake/mips.cmake /toolchains
