FROM ahuszagh/cross:base

# Build GCC
COPY android.sh /
RUN /android.sh

RUN rm /android.sh

# Add toolchains
COPY cmake/armv7a-unknown-linux-androideabi.cmake /toolchains
COPY cmake/armv7a-unknown-linux-androideabi.cmake /toolchains/armv7a.cmake
COPY env/armv7a-unknown-linux-androideabi /toolchains/env
