FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-s390x-linux-gnu \
    libc6-s390-s390x-cross

COPY cmake/s390x-unknown-linux-gnu.cmake /toolchains
COPY cmake/s390x-unknown-linux-gnu.cmake /toolchains/s390x.cmake
COPY env/s390x-unknown-linux-gnu /toolchains/env
