FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mipsisa32r6el-linux-gnu \
    libc6-mipsr6el-cross

COPY cmake/mipsr6el.cmake /toolchains
