FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/alphaev6-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=alphaev6-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/alphaev6-unknown.cmake /toolchains
#COPY cmake/alphaev6-unknown.cmake /toolchains/alphaev6.cmake
#COPY env/alphaev6-unknown /toolchains/env
