FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/powerpcle-unknown-linux-gnu.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=powerpcle-unknown-linux-gnu /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/ppcle-unknown-linux-gnu.sh /
RUN /ppcle-unknown-linux-gnu.sh
RUN rm /shortcut.sh /ppcle-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/ppcle-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
