FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mipsisa64r6el-linux-gnuabi64 \
    libc6-mips64r6el-cross

COPY cmake/mips64r6el.cmake /toolchains
