FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/x86_64-multilib-linux-musl.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=x86_64-multilib-linux-musl /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
COPY cmake/x86_64-multilib-linux-musl.cmake /toolchains
COPY cmake/x86_64-multilib-linux-musl.cmake /toolchains/x86_64.cmake
COPY env/x86_64-multilib-linux-musl /toolchains/env
