FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/x86_64-multilib-linux-musl.config /ct-ng/
COPY ct-ng/adduser.sh /ct-ng/
RUN /ct-ng/adduser.sh
COPY ct-ng/install-deps.sh /ct-ng/
RUN /ct-ng/install-deps.sh
COPY ct-ng/build-ctng.sh /ct-ng/
RUN /ct-ng/build-ctng.sh
COPY ct-ng/cp-config.sh /ct-ng/
RUN ARCH=x86_64-multilib-linux-musl /ct-ng/cp-config.sh
COPY ct-ng/build-cross.sh /ct-ng/
RUN /ct-ng/build-cross.sh
COPY ct-ng/clean.sh /ct-ng/
RUN /ct-ng/clean.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
COPY cmake/x86_64-multilib-linux-musl.cmake /toolchains
COPY cmake/x86_64-multilib-linux-musl.cmake /toolchains/x86_64.cmake
COPY env/x86_64-multilib-linux-musl /toolchains/env
