FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mipsisa64r6-linux-gnuabi64 \
    libc6-mips64r6-cross

COPY cmake/mips64r6.cmake /toolchains
