FROM ahuszagh/cross:base

# Build GCC
COPY android.sh /
RUN /android.sh

RUN rm /android.sh

# Add toolchains
COPY cmake/aarch64-unknown-linux-android.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains
COPY cmake/static.cmake /toolchains
COPY env/aarch64-unknown-linux-android /env/toolchain
COPY env/alias /env
COPY env/shared /env
COPY env/static /env
