FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/powerpcle-unknown-eabi.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=powerpcle-unknown-eabi /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
COPY cmake/ppcle-unknown-eabi.cmake /toolchains
COPY cmake/ppcle-unknown-eabi.cmake /toolchains/ppcle.cmake
COPY env/ppcle-unknown-eabi /toolchains/env
