FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/ppcle-unknown-spe.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=ppcle-unknown-spe /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/ppcle-unknown-spe.cmake /toolchains
#COPY cmake/ppcle-unknown-spe.cmake /toolchains/ppcle.cmake
#COPY env/ppcle-unknown-spe /toolchains/env
