FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/sh4-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=sh4-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/sh4-unknown.cmake /toolchains
#COPY cmake/sh4-unknown.cmake /toolchains/sh4.cmake
#COPY env/sh4-unknown /toolchains/env
