FROM ahuszagh/cross:base

# Build GCCCOPY ct-ng/avr.config /ct-ng/
COPY ct-ng/powerpcle-unknown-elf.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=powerpcle-unknown-elf /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
COPY cmake/ppcle-unknown-elf.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains
COPY cmake/static.cmake /toolchains
COPY env/ppcle-unknown-elf /env/toolchain
COPY env/alias /env
COPY env/shared /env
COPY env/static /env
