FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mips64el-linux-gnuabi64 \
    libc6-mips64el-cross

COPY cmake/mips64el-unknown-linux-gnu.cmake /toolchains
COPY cmake/mips64el-unknown-linux-gnu.cmake /toolchains/mips64el.cmake
COPY env/mips64el-unknown-linux-gnu /toolchains/env
