FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-sparc64-linux-gnu \
    libc6-sparc64-cross

COPY cmake/sparc64-unknown-linux-gnu.cmake /toolchains
COPY cmake/sparc64-unknown-linux-gnu.cmake /toolchains/sparc64.cmake
COPY env/sparc64-unknown-linux-gnu /toolchains/env
