FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/xtensale-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=xtensale-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/xtensale-unknown.cmake /toolchains
#COPY cmake/xtensale-unknown.cmake /toolchains/xtensale.cmake
#COPY env/xtensale-unknown /toolchains/env
