FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/xtensabe-unknown-linux-uclibc.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=xtensabe-unknown-linux-uclibc /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Restore...
## Add toolchains
#COPY cmake/xtensabe-unknown-linux-uclibc.cmake /toolchains
#COPY cmake/xtensabe-unknown-linux-uclibc.cmake /toolchains/xtensabe.cmake
#COPY env/xtensabe-unknown-linux-uclibc /toolchains/env
