FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/arcle-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=arcle-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/arcle-unknown.cmake /toolchains
#COPY cmake/arcle-unknown.cmake /toolchains/arcle.cmake
#COPY env/arcle-unknown /toolchains/env
