FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/alphaev56-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=alphaev56-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/alphaev56-unknown.cmake /toolchains
#COPY cmake/alphaev56-unknown.cmake /toolchains/alphaev56.cmake
#COPY env/alphaev56-unknown /toolchains/env
