FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/arcle-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=arcle-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/arcle-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
#COPY cmake/shared.cmake /toolchains
#COPY cmake/static.cmake /toolchains
#COPY env/arcle-unknown-linux-gnu /env/toolchain
#COPY env/alias /env
#COPY env/shared /env
#COPY env/static /env
