FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/ppc64-unknown-eabi.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=ppc64-unknown-eabi /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Add symlinks and toolchains
