FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mips64-linux-gnuabi64 \
    libc6-mips64-cross

COPY cmake/mips64.cmake /toolchains
