FROM ahuszagh/cross:qemu

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-riscv64-linux-gnu \
    libc6-riscv64-cross

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/riscv64-unknown-linux-gnu.sh /
RUN /riscv64-unknown-linux-gnu.sh
RUN rm /shortcut.sh /riscv64-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/riscv64-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY cmake/static.cmake /toolchains/riscv64.cmake
COPY env/shared /env/
COPY env/static /env/
