FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/mipsel-unknown-o32.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=mipsel-unknown-o32 /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Add symlinks and toolchains
