FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/x86_64-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=x86_64-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/x86_64-unknown.cmake /toolchains
#COPY cmake/x86_64-unknown.cmake /toolchains/x86_64.cmake
#COPY env/x86_64-unknown /toolchains/env
