FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mipsel-linux-gnu \
    libc6-mipsel-cross

# Add symlinks
COPY symlink/exec.sh /
COPY symlink/mipsel-unknown-linux-gnu.sh /
RUN /mipsel-unknown-linux-gnu.sh
RUN rm /exec.sh /mipsel-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/mipsel-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
