FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/ppc64-unknown-eabi.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=ppc64-unknown-eabi /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/ppc64-unknown-eabi.cmake /toolchains/toolchain.cmake
#COPY cmake/shared.cmake /toolchains
#COPY cmake/static.cmake /toolchains
#COPY env/ppc64-unknown-eabi /env/toolchain
#COPY env/alias /env
#COPY env/shared /env
#COPY env/static /env
