FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/alphaev45-unknown.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=alphaev45-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/alphaev45-unknown.cmake /toolchains
#COPY cmake/alphaev45-unknown.cmake /toolchains/alphaev45.cmake
#COPY env/alphaev45-unknown /toolchains/env
