FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-arm-linux-gnueabihf \
    libc6-armel-armhf-cross

COPY cmake/armelhf-unknown-linux-gnu.cmake /toolchains
COPY cmake/armelhf-unknown-linux-gnu.cmake /toolchains/armelhf.cmake
COPY env/armelhf-unknown-linux-gnu /toolchains/env
