FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/ppc64le-unknown-spe.config /ct-ng/
COPY gcc.sh /ct-ng/
RUN ARCH=ppc64le-unknown-spe /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/ppc64le-unknown-spe.cmake /toolchains
#COPY cmake/ppc64le-unknown-spe.cmake /toolchains/ppc64le.cmake
#COPY env/ppc64le-unknown-spe /toolchains/env
