# Base image for all other images.

FROM ubuntu:^UBUNTU_VERSION^

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    autoconf \
    ca-certificates \
    cmake \
    git \
    make \
    ninja-build

RUN mkdir -p /env
RUN mkdir -p ^BIN^
RUN mkdir -p /toolchains
COPY ["cmake/cmake", ^BIN^]

# Add non-root user to build libraries to and for xcross.
RUN adduser --disabled-password --gecos "" crosstoolng
