# Build image with package managers pre-installed.
FROM ^USERNAME^/^REPOSITORY^:^TARGET^

COPY ["docker/conan.sh", "/"]
COPY ["docker/meson.sh", "/"]
COPY ["docker/vcpkg.sh", "/"]
RUN COMPILER=^COMPILER^ COMPILER_VERSION=^COMPILER_VERSION^ SYSTEM=^CONAN_SYSTEM^ TRIPLE=^TRIPLE^ /conan.sh
RUN CPU_FAMILY=^CPU_FAMILY^ PROCESSOR=^PROCESSOR^ SYSTEM=^MESON_SYSTEM^ /meson.sh
RUN LINKAGE=^LINKAGE^ PROCESSOR=^PROCESSOR^ SYSTEM=^VCPKG_SYSTEM^ TRIPLE=^TRIPLE^ /vcpkg.sh
RUN rm /conan.sh /meson.sh /vcpkg.sh
