# Create an install with vcpkg as a single layer.
# Allows a single vcpkg build, rather rebuild
# for every image. This image should never change.
COPY ["docker/vcpkg.sh", "/"]
RUN /vcpkg.sh
RUN rm /vcpkg.sh
