FROM ahuszagh/cross:base

# Install build packages

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-powerpc-linux-gnu \
    libc6-powerpc-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=ppc /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/ppc-unknown-linux-gnu.sh /
RUN /ppc-unknown-linux-gnu.sh
RUN rm /shortcut.sh /ppc-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/ppc-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
