FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/arc-unknown.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=arc-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Add symlinks and toolchains
