FROM ahuszagh/cross:qemu

# Build GCC
COPY ct-ng/i686-unknown-linux-uclibc.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=i686-unknown-linux-uclibc /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/i686-unknown-linux-uclibc.sh /
RUN /i686-unknown-linux-uclibc.sh
RUN rm /shortcut.sh /i686-unknown-linux-uclibc.sh

# Add toolchains
COPY cmake/i686-unknown-linux-uclibc.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
