FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/moxie-none-elf.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=moxie-none-elf /ct-ng/gcc.sh
RUN rm -rf /ct-ng/

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/moxie-none-elf.sh /
RUN /moxie-none-elf.sh
RUN rm /shortcut.sh /moxie-none-elf.sh

# Add toolchains
COPY cmake/moxie-none-elf.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
