FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/arcbe-unknown-linux-uclibc.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=arcbe-unknown-linux-uclibc /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/arcbe-unknown-linux-uclibc.sh /
RUN /arcbe-unknown-linux-uclibc.sh
RUN rm /shortcut.sh /arcbe-unknown-linux-uclibc.sh

# Add toolchains
COPY cmake/arcbe-unknown-linux-uclibc.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
