FROM ahuszagh/cross:base

# Install build packages

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-s390x-linux-gnu \
    libc6-s390-s390x-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=s390x /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/s390x-unknown-linux-gnu.sh /
RUN /s390x-unknown-linux-gnu.sh
RUN rm /shortcut.sh /s390x-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/s390x-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
