FROM ahuszagh/cross:base

# Install build packages

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mipsisa32r6el-linux-gnu \
    libc6-mipsr6el-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=mipsel /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/mipsr6el-unknown-linux-gnu.sh /
RUN /mipsr6el-unknown-linux-gnu.sh
RUN rm /shortcut.sh /mipsr6el-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/mipsr6el-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
