FROM emscripten/emsdk:2.0.23

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    autoconf \
    ca-certificates \
    cmake \
    git \
    make \
    ninja-build

RUN mkdir -p /env
RUN mkdir -p ^BIN^
RUN mkdir -p /toolchains

# Copy over build tool wrappers.
COPY ["cmake/emcmake", "^BINDIR^/cmake"]
COPY ["symlink/emmake", "^BINDIR^/make"]
WORKDIR /
