FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/microblazeel-xilinx-linux-gnu.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=microblazeel-xilinx-linux-gnu /ct-ng/gcc.sh
RUN rm -rf /ct-ng/

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=microblazeel /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/microblazeel-xilinx-linux-gnu.sh /
RUN /microblazeel-xilinx-linux-gnu.sh
RUN rm /shortcut.sh /microblazeel-xilinx-linux-gnu.sh

# Add toolchains
COPY cmake/microblazeel-xilinx-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
