FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mipsel-linux-gnu \
    libc6-mipsel-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=mipsel /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/mipsel-unknown-linux-gnu.sh /
RUN /mipsel-unknown-linux-gnu.sh
RUN rm /shortcut.sh /mipsel-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/mipsel-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
