# Base image for all other images.

FROM ubuntu:20.04

RUN apt update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    cmake \
    git \
    ca-certificates \
    make

RUN mkdir -p /toolchains
RUN mkdir -p /env

# Add non-root user to build libraries to and for x-cross.
RUN adduser --disabled-password --gecos "" crosstoolng