FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/mips64el-unknown-n64.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=mips64el-unknown-n64 /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Add symlinks and toolchains
