FROM ahuszagh/cross:base

# Build GCC
COPY docker/riscv-gcc.sh /
RUN ARCH=riscv64-unknown-linux-gnu /riscv-gcc.sh
RUN rm /riscv-gcc.sh

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=riscv64 /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/riscv64-multilib-linux-gnu.sh /
RUN /riscv64-multilib-linux-gnu.sh
RUN rm /shortcut.sh /riscv64-multilib-linux-gnu.sh

# Add toolchains
COPY cmake/riscv64-multilib-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
