FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/x86_64-multilib-linux-musl.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=x86_64-multilib-linux-musl /ct-ng/gcc.sh
RUN rm -rf /ct-ng/

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=i386 /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/i686-multilib-linux-musl.sh /
RUN /i686-multilib-linux-musl.sh
RUN rm /shortcut.sh /i686-multilib-linux-musl.sh

# Add toolchains
COPY cmake/i686-multilib-linux-musl.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
