FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/alphaev5-unknown-elf.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=alphaev5-unknown-elf /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Add symlinks and toolchains
