FROM ahuszagh/cross:base

# Install build packages
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mips-linux-gnu \
    libc6-mips-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=mips /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/mips-unknown-linux-gnu.sh /
RUN /mips-unknown-linux-gnu.sh
RUN rm /shortcut.sh /mips-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/mips-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
