FROM ahuszagh/cross:base

# Install build packages
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-mips64-linux-gnuabi64 \
    libc6-mips64-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=mips64 /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/mips64-unknown-linux-gnu.sh /
RUN /mips64-unknown-linux-gnu.sh
RUN rm /shortcut.sh /mips64-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/mips64-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
