FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/ppc64le-unknown-spe.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=ppc64le-unknown-spe /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Add symlinks and toolchains
