FROM ahuszagh/cross:qemu

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-sh4-linux-gnu \
    libc6-sh4-cross

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/sh4-unknown-linux-gnu.sh /
RUN /sh4-unknown-linux-gnu.sh
RUN rm /shortcut.sh /sh4-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/sh4-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
