FROM ahuszagh/cross:qemu

# Build GCC
COPY ct-ng/x86_64-multilib-linux-musl.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=x86_64-multilib-linux-musl /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/x86_64-multilib-linux-musl.sh /
RUN /x86_64-multilib-linux-musl.sh
RUN rm /shortcut.sh /x86_64-multilib-linux-musl.sh

# Add toolchains
COPY cmake/x86_64-multilib-linux-musl.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
