# Install JQ to pretty print JSON.
RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    jq

COPY ["spec/target_features.py", "/"]
COPY ["spec/target_features.sh", "/"]
RUN ARCH=^ARCH^ OS=^OS^ FLAGS=^FLAGS^ OPTIONAL_FLAGS=^OPTIONAL_FLAGS^ CC=^CC^ CXX=^CXX^ LINKER=^LINKER^ /target_features.sh
RUN rm /target_features.py
RUN rm /target_features.sh
