FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/xtensabe-unknown-linux-uclibc.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=xtensabe-unknown-linux-uclibc /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Add symlinks and toolchains
