FROM ahuszagh/cross:base

# Build GCC
COPY docker/android.sh /
RUN ARCH=armv7a-linux-androideabi /android.sh
RUN rm /android.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/armv7a-unknown-linux-androideabi.sh /
RUN /armv7a-unknown-linux-androideabi.sh
RUN rm /shortcut.sh /armv7a-unknown-linux-androideabi.sh

# Add toolchains
COPY cmake/armv7a-unknown-linux-androideabi.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
