FROM ahuszagh/cross:base

# Install build packages
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-aarch64-linux-gnu \
    libc6-arm64-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=aarch64 /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/arm64-unknown-linux-gnu.sh /
RUN /arm64-unknown-linux-gnu.sh
RUN rm /shortcut.sh /arm64-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/arm64-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
