FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-hppa-linux-gnu \
    libc6-hppa-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=hppa /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/hppa-unknown-linux-gnu.sh /
RUN /hppa-unknown-linux-gnu.sh
RUN rm /shortcut.sh /hppa-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/hppa-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
