FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/sparc64-unknown.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=sparc64-unknown /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# Add toolchains
# TODO(ahuszagh) Restore
#COPY cmake/sparc64-unknown-elf.cmake /toolchains/toolchain.cmake
#COPY cmake/shared.cmake /toolchains
#COPY cmake/static.cmake /toolchains
#COPY env/sparc64-unknown-elf /env/toolchain
#COPY env/alias /env
#COPY env/shared /env
#COPY env/static /env
