FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/avr.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=avr /ct-ng/gcc.sh
RUN rm -rf /ct-ng/

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/avr.sh /
RUN /avr.sh
RUN rm /shortcut.sh /avr.sh

# Add toolchains
COPY cmake/avr.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
