FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/nios2-none-elf.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=nios2-none-elf /ct-ng/gcc.sh
RUN rm -rf /ct-ng/

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/nios2-none-elf.sh /
RUN /nios2-none-elf.sh
RUN rm /shortcut.sh /nios2-none-elf.sh

# Add toolchains
COPY cmake/nios2-none-elf.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
