FROM ahuszagh/cross:base

# Build GCC
COPY docker/riscv-gcc.sh /
RUN ARCH=riscv64-unknown-elf /riscv-gcc.sh
RUN rm /riscv-gcc.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/riscv64-unknown-elf.sh /
RUN /riscv64-unknown-elf.sh
RUN rm /shortcut.sh /riscv64-unknown-elf.sh

# Add toolchains
COPY cmake/riscv64-unknown-elf.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
