FROM ahuszagh/cross:base

# Install build packages
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-powerpc64le-linux-gnu \
    libc6-ppc64el-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=ppc64le /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/ppc64le-unknown-linux-gnu.sh /
RUN /ppc64le-unknown-linux-gnu.sh
RUN rm /shortcut.sh /ppc64le-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/ppc64le-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
