FROM ahuszagh/cross:base

# Build GCC
COPY docker/android.sh /
RUN /android.sh
RUN rm /android.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/i686-unknown-linux-android.sh /
RUN /i686-unknown-linux-android.sh
RUN rm /shortcut.sh /i686-unknown-linux-android.sh

# Add toolchains
COPY cmake/i686-unknown-linux-android.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
