FROM ahuszagh/cross:base

# Install build packages
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-arm-linux-gnueabihf \
    libc6-armel-armhf-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=arm /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/thumbelhf-unknown-linux-gnueabi.sh /
RUN /thumbelhf-unknown-linux-gnueabi.sh
RUN rm /shortcut.sh /thumbelhf-unknown-linux-gnueabi.sh

# Add toolchains
COPY cmake/thumbelhf-unknown-linux-gnueabi.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
