# Add toolchains
COPY ["cmake/toolchain/^TARGET^.cmake", "/toolchains/toolchain.cmake"]
# This step is mostly for backward compatibility.
COPY ["cmake/toolchain/^TARGET^.cmake", "/toolchains/^ARCH^.cmake"]
COPY ["cmake/shared.cmake", "/toolchains/"]
COPY ["cmake/static.cmake", "/toolchains/"]
COPY ["env/base", "/env/"]
COPY ["env/replace", "/env/"]
COPY ["env/shared", "/env/"]
COPY ["env/static", "/env/"]
