FROM ahuszagh/cross:base

# Install build packages

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10 \
    libc6

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=x86_64 /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/x86_64-unknown-linux-gnu.sh /
RUN /x86_64-unknown-linux-gnu.sh
RUN rm /shortcut.sh /x86_64-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/x86_64-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
