FROM ahuszagh/cross:base

RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-arm-linux-gnueabi \
    libc6-armel-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=arm /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/armel-unknown-linux-gnueabi.sh /
RUN /armel-unknown-linux-gnueabi.sh
RUN rm /shortcut.sh /armel-unknown-linux-gnueabi.sh

# Add toolchains
COPY cmake/armel-unknown-linux-gnueabi.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
