FROM ahuszagh/cross:base

# Build GCC
COPY ct-ng/moxiebox-none-moxie.config /ct-ng/
COPY docker/gcc.sh /ct-ng/
RUN ARCH=moxiebox-none-moxie /ct-ng/gcc.sh

# Remove GCC build scripts and config.
RUN rm -rf /ct-ng/

# TODO(ahuszagh) Add toolchains, etc.
