FROM ahuszagh/cross:base

# Install build packages
RUN DEBIAN_FRONTEND="noninteractive" apt-get install --assume-yes --no-install-recommends \
    g++-10-alpha-linux-gnu \
    libc6.1-alpha-cross

# Add Qemu binaries.
COPY docker/qemu-apt.sh /
RUN ARCH=alpha /qemu-apt.sh
RUN rm /qemu-apt.sh

# Add symlinks
COPY symlink/shortcut.sh /
COPY symlink/alpha-unknown-linux-gnu.sh /
RUN /alpha-unknown-linux-gnu.sh
RUN rm /shortcut.sh /alpha-unknown-linux-gnu.sh

# Add toolchains
COPY cmake/alpha-unknown-linux-gnu.cmake /toolchains/toolchain.cmake
COPY cmake/shared.cmake /toolchains/
COPY cmake/static.cmake /toolchains/
COPY env/shared /env/
COPY env/static /env/
