CMAKE_MINIMUM_REQUIRED(VERSION 3.3)
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR alpha)

SET(CMAKE_FIND_ROOT_PATH "/usr/alpha-linux-gnu/")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CROSSCOMPILING_EMULATOR "run")
