SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR arm64)
SET(ARCH 64)

SET(CMAKE_COMPILER_PREFIX "aarch64-linux-gnu-")
SET(CMAKE_FIND_ROOT_PATH "/usr/aarch64-linux-gnu/")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
