set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR armhf)

# COMPILERS
# ---------
SET(CMAKE_C_COMPILER arm-linux-gnueabihf-gcc-10)
SET(CMAKE_CXX_COMPILER arm-linux-gnueabihf-g++-10)
set(CMAKE_COMPILER_PREFIX arm-linux-gnueabihf-)

# PATHS
# -----
set(CMAKE_FIND_ROOT_PATH /usr/arm-linux-gnueabihf/)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# OTHER
# -----
set(ARCH 32)
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")
