set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

# COMPILERS
# ---------
SET(CMAKE_C_COMPILER arm-linux-gnueabi-gcc-10)
SET(CMAKE_CXX_COMPILER arm-linux-gnueabi-g++-10)
set(CMAKE_COMPILER_PREFIX arm-linux-gnueabi-)

# PATHS
# -----
set(CMAKE_FIND_ROOT_PATH /usr/arm-linux-gnueabi/)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# OTHER
# -----
set(ARCH 32)
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")
