SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR armv7a)
SET(ARCH 32)

SET(CMAKE_COMPILER_PREFIX "armv7a-linux-androideabi-")
SET(CMAKE_FIND_ROOT_PATH "/usr/local/toolchains/llvm/prebuilt/linux-x86_64/")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
