SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR i686)
SET(ARCH 32)

SET(CMAKE_COMPILER_PREFIX "i686-linux-android-")
SET(CMAKE_FIND_ROOT_PATH "/usr/local/toolchains/llvm/prebuilt/linux-x86_64/")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
