SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR mipsisa64r6el)
SET(ARCH 64)

SET(CMAKE_COMPILER_PREFIX "mipsisa64r6el-linux-gnuabi64-")
SET(CMAKE_FIND_ROOT_PATH "/usr/mipsisa64r6el-linux-gnuabi64/")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
