set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR mips64el)

# COMPILERS
# ---------
SET(CMAKE_C_COMPILER mips64el-linux-gnuabi64-gcc-10)
SET(CMAKE_CXX_COMPILER mips64el-linux-gnuabi64-g++-10)
set(CMAKE_COMPILER_PREFIX mips64el-linux-gnuabi64-)

# PATHS
# -----
set(CMAKE_FIND_ROOT_PATH /usr/mips64el-linux-gnuabi64/)
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# OTHER
# -----
set(ARCH 64)
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS}")
SET(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")
