SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR mips64el)
SET(ARCH 64)

SET(CMAKE_COMPILER_PREFIX "mips64el-linux-gnuabi64-")
SET(CMAKE_FIND_ROOT_PATH "/usr/mips64el-linux-gnuabi64/")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
