SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR s390x)
SET(ARCH 64)

SET(CMAKE_COMPILER_PREFIX "s390x-linux-gnu-")
SET(CMAKE_FIND_ROOT_PATH "/usr/s390x-linux-gnu/")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
