SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_PROCESSOR sh4)
SET(ARCH 32)

SET(CMAKE_COMPILER_PREFIX "sh4-linux-gnu-")
SET(CMAKE_FIND_ROOT_PATH "/usr/sh4-linux-gnu/")
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
